name: Test
on: push
jobs:

  integration:
    name: Integration test
    runs-on: ubuntu-latest
    steps:

    - name: Setup for integration test
      run: sudo npm install -g newman # ポイント②

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the docker-compose stack # Docker Composeを実行
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

    - name: Sleep to wait for preparing of containers
      run: sleep 15 # ポイント③

    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

#    - name: Run test suite #Newmanコマンドを実行しテスト実施
#      run: newman run -e Local.postman_environment.json postman_collection.json