name: Test
on: push
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3800 # Optional, default value is 3306. The port of host
          container port: 3307 # Optional, default value is 3306. The port of container
          character set server: 'utf8mb4' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'great_db' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'mysql' # Required if "mysql user" is empty, default is empty. The root superuser password
      - name: Build the docker-compose stack # Docker Composeを実行
        run: docker-compose -f docker-compose.yml up -d
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
