name: MySQL service example
on: push

jobs:
  # コンテナジョブのラベル
  container-job:
    # コンテナは Linux ベースのオペレーティングシステムで実行しなければならない
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: mintaku
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
    # `container-job` が実行される Docker Hub イメージ

    steps:
      - name: Set up MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
      # CI テストを実行する前に、リポジトリにコードのコピーをダウンロードする
      - name: Check out repository code
        uses: actions/checkout@v2

      # `package.json` ファイル内のすべての依存関係のクリーンインストールを実行する
      # 詳しい情報については https://docs.npmjs.com/cli/ci.html を参照
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Connect to MySQL
        run: python client.py

        env:
          # MySQLサービスコンテナとの通信に使われるホスト名
          MYSQL_HOST: mysql
          # デフォルトのPostgreSQLポート
          MYSQL_PORT: 3306